const dall = [
  {
    id: 1,
    image: "./d1.webp",
    name: "Young Girl Elegant Sweet Yellow Dress",
    description: "Description: 1. Neck",
    size: ["1T", "2T", "3T", "4T", "5T"],
    color: ["Yellow"],
    price: "358.000 VNĐ",
  },
  {
    id: 2,
    image: "./d2.webp",
    name: "Young Girl Elegant Sweet Black Dress",
    description: "",
    size: ["1T", "2T", "3T", "4T", "5T"],
    color: "Black",
    price: "356.000 VNĐ",
  },

  {
    id: 3,
    image: "./d3.webp",
    name: "Young Girl Ditsy Floral Chiffon Slip Dress",
    description: "Summer vacation and your child.",
    size: ["2T", "3T", "4T", "5T"],
    color: "White Coral",
    price: "580.000 VNĐ",
  },
  {
    id: 4,
    image: "./d4.webp",
    name: "Two pieces cutie for baby",
    description: "",
    size: ["2T", "3T", "4T", "5T"],
    color:  ["Yellow"],
    price: "250.000 VNĐ",
  },
  {
    id: 5,
    image: "./d5.webp",
    name: "Girls' Minimalist Casual Fashion Versatile Pleated Sleeveless Dress",
    description: "",
    size: ["2T", "3T", "4T", "5T"],
    color: "White",
    price: "800.000 VNĐ",
  },
  {
    id: 6,
    image: "./d6.webp",
    name: "Baby Girl Contrast Mesh Embroidery Design Short Puff Sleeve Cute Dress",
    description: "",
    size: ["2T", "3T", "4T", "5T"],
    color:  ["Yellow"],
    price: "390.000 VNĐ",
  },
  {
    id: 7,
    image: "./d7.webp",
    name: "Young Girls Yellow Sleeveless Ruffle Trim Floral Mesh Patchwork Sleeveless Princess Dress, Sweet Casual Summer Beach Vacation ",
    description: "",
    size: ["2T", "3T", "4T", "5T"],
    color:  ["Yellow"],
    price: "240.000 VNĐ",
  },
  {
    id: 8,
    image: "./d8.webp",
    name: "1pc Girls Mini Fresh Lemon Ditsy Floral Square Collar Puff Sleeve Dress, Spring/Summer",
    description: "",
    size: ["2T", "3T", "4T", "5T"],
    color: "White Coral",
    price: "200.000 VNĐ",
  },

  {
    id: 9,
    image: "./d9.webp",
    name: "Vintaside Kids Girl Yellow & White Contrast Color Elegant Simple Short Puff",
    description: "",
    size: ["2T", "3T", "4T", "5T"],
    color:  ["Yellow"],
    price: "520.000 VNĐ",
  },

  {
    id: 10,
    image: "./d10.webp",
    name: "Young Girls Spring/Summer Embroidered Ruffle Collar & Puff Sleeve Design Dress, Suitable For School Daily Wear And Vacation",
    description: "",
    size: ["2T", "3T", "4T", "5T"],
    color:  ["Yellow"],
    price: "680.000 VNĐ",
  },

  {
    id: 11,
    image: "./d11.webp",
    name: "Young Girl Solid Color Knit Sweet Casual Puff Sleeve A-Line Dress With Round Neck",
    size: ["2T", "3T", "4T", "5T"],
    color:  ["Yellow"],
    price: "200.000 VNĐ",
  },

  {
    id: 12,
    image: "./d12.webp",
    name: "Floral Embroidery Peter Pan Collar Puff Sleeve Single-Breasted Casual Dress For Young Girl",
    description: "",
    size: ["2T", "3T", "4T", "5T"],
    color:  ["Yellow"],
    price: "350.000 VNĐ",
  },

  {
    id: 13,
    image: "./d13.webp",
    name: "Souflis Souflis Adorable And Sweet Young Girl Solid Color Dress With Large Bowknot",
    description: "",
    size: ["2T", "3T", "4T", "5T"],
    color:  ["Yellow"],
    price: "450.000 VNĐ",
  },

  {
    id: 14,
    image: "./d14.webp",
    name: "Plaid Peter Pan Collar Short Sleeve Dress Yellow ",
    description: "",
    size: ["2T", "3T", "4T", "5T"],
    color:  ["Yellow"],
    price: "200.000 VNĐ",
  },

  {
    id: 15,
    image: "./d15.webp",
    name: "Souflis Girls' Vacation Party Puff Sleeve Bow Accent Collared A-Line Dress",
    description: "",
    size: ["2T", "3T", "4T", "5T"],
    color: "Yellow",
    price: "470.000 VNĐ",
  },

  {
    id: 16,
    image: "./d16.webp",
    name: "Blossori Young Girls' Rustic Vacation Ruffle Trim Puff Sleeve Dress",
    description: "",
    size: ["2T", "3T", "4T", "5T"],
    color: "Yellow",
    price: "360.000 VNĐ",
  },
  {
    id: 17,
    image: "./d17.webp",
    name: "Light Yellow Peter Pan Collar Puff Sleeve Dress With Cute Cartoon 3D Flower Bouquet Decor",
    description: "",
    size: ["2T", "3T", "4T", "5T"],
    color: "Yellow",
    price: "520.000 VNĐ",
  },
  {
    id: 18,
    image: "./d18.webp",
    name: "Young Girl Elegant Lovely Forest Girl Style Casual Versatile Classic Lace Hollow Floral Ruffle Collar Long Sleeve Dress",
    description: "",
    size: ["2T", "3T", "4T", "5T"],
    color: "White",
    price: "630.000 VNĐ",
  },
  {
    id: 19,
    image: "./d19.webp",
    name: "Girls Spring/Autumn New Lace Pleated Shirt Long Sleeve & A-Line Ruffle Hem Skirt Set",
    description: "",
    size: ["2T", "3T", "4T", "5T"],
    color: "Yellow",
    price: "390.000 VNĐ",
  },
  {
    id: 20,
    image: "./d20.webp",
    name: "Young Girls Apricot Ruffle Trim A-Line Dress",
    description: "",
    size: ["2T", "3T", "4T", "5T"],
    color: "White",
    price: "490.000 VNĐ",
  },
  {
    id: 21,
    image: "./d21.webp",
    name: "Vintaside Kids Girls' Sweet Puff Sleeve Floral Textured Waist Fit Dress",
    description: "",
    size: ["2T", "3T", "4T", "5T"],
    color: "Yellow",
    price: "250.000 VNĐ",
  },
  {
    id: 22,
    image: "./d22.webp",
    name: "Girls Elegant Princess Ruffled Collar Bubble Long Sleeve Jacquard Embroidered Double Layer Ruffled Hem Loose Princess Dress",
    description: "",
    size: ["2T", "3T", "4T", "5T"],
    color: "White",
    price: "300.000 VNĐ",
  },
  {
    id: 23,
    image: "./d23.webp",
    name: "Young Girl Round Neck Sleeveless Halter Cute Dress, Summer",
    description: "",
    size: ["2T", "3T", "4T", "5T"],
    color: "Yellow",
    price: "200.000 VNĐ",
  },
  {
    id: 24,
    image: "./d24.webp",
    name: "Young Girl Spring Summer Square Neck Short Sleeve Woven Dress",
    description: "",
    size: ["2T", "3T", "4T", "5T"],
    color: "White",
    price: "310.000 VNĐ",
  },
  {
    id: 25,
    image: "./d25.webp",
    name: "Young Girl Floral Print Flounce Sleeve Ruffle Hem Dress",
    description: "",
    size: ["2T", "3T", "4T", "5T"],
    color: "White Coral",
    price: "360.000 VNĐ",
  },
  {
    id: 26,
    image: "./d26.webp",
    name: "Young Girl Casual Sleeveless Waist Gathered Hollow Out Embroidery Decor Midi Dress",
    description: "",
    size: ["2T", "3T", "4T", "5T"],
    color: "White",
    price: "320.000 VNĐ",
  },
  {
    id: 27,
    image: "./d27.webp",
    name: "Girl Elegant Solid Color Jacquard Patchwork Sleeveless Dress",
    description: "",
    size: ["2T", "3T", "4T", "5T"],
    color: "White",
    price: "370.000 VNĐ",
  },
  {
    id: 28,
    image: "./d28.webp",
    name: "rl Minimalist Casual Short Sleeve Dress For Daily Wear Floral",
    description: "",
    size: ["2T", "3T", "4T", "5T"],
    color: "White Coral",
    price: "480.000 VNĐ",
  },
  {
    id: 29,
    image: "./d29.webp",
    name: "Girl's Cap Sleeve Mesh Princess Dress",
    description: "",
    size: ["2T", "3T", "4T", "5T"],
    color: "Yellow",
    price: "1.560.000 VNĐ",
  },
  {
    id: 30,
    image: "./d30.webp",
    name: "Girl' Elegant Embroidered Puffy Sleeve Princess Party Dress",
    description: "",
    size: ["2T", "3T", "4T", "5T"],
    color: "Yellow",
    price: "2.952.000 VNĐ",
  },
];

export default dall;